language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --all --verbose
  - cargo build --all --verbose --target wasm32-unknown-unknown
  - cargo test --all --verbose
